//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryProject.classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class loanhistory2
    {
        public string historyID { get; set; }
        public Nullable<int> memberID { get; set; }
        public Nullable<int> matID { get; set; }
    
        public virtual material material { get; set; }
        public virtual member_DB member_DB { get; set; }
    }
}
