//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryProject.classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public material()
        {
            this.reserveds = new HashSet<reserved>();
            this.loan_DB2 = new HashSet<loan_DB2>();
            this.loanhistory2 = new HashSet<loanhistory2>();
        }
    
        public int matID { get; set; }
        public Nullable<int> typeID { get; set; }
        public Nullable<int> langID { get; set; }
        public Nullable<int> publisherID { get; set; }
        public Nullable<int> catID { get; set; }
        public Nullable<int> branchID { get; set; }
        public string name { get; set; }
        public string title { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> pageNo { get; set; }
        public string description { get; set; }
        public Nullable<bool> avaible { get; set; }
    
        public virtual branch branch { get; set; }
        public virtual category category { get; set; }
        public virtual language language { get; set; }
        public virtual publisher publisher { get; set; }
        public virtual type type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reserved> reserveds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<loan_DB2> loan_DB2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<loanhistory2> loanhistory2 { get; set; }
    }
}
