//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryProject.classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class penaltyDB3
    {
        public int @int { get; set; }
        public Nullable<int> memID { get; set; }
        public Nullable<int> matID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
