//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryProject.classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public int staffID { get; set; }
        public string name { get; set; }
        public string surnam { get; set; }
        public string mail { get; set; }
        public string number { get; set; }
        public string adress { get; set; }
        public Nullable<int> workDepID { get; set; }
    
        public virtual staffDepartmant staffDepartmant { get; set; }
    }
}
